# -*- coding: utf-8 -*-
"""Copy of Lab #1: Numeric Variables

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iBkBc9CZNz7TyxlL1vkbgFjxFcOPpPXU
"""

print('Lab #1, Numeric Variables.\n')
print("Prompt #1, Prompt #2, & Prompt #3:\n")

# the input function is so that users can type in the numbers
var_1 = int(input('Enter the value of var_1:\n'))
var_2 = float(input('Enter the value of var_2:\n'))
var_3 = float(input('Enter the value of var_3:\n'))
var_4 = float(input('Enter the value of var_4:\n'))

# override var_2 & printing var_2
over_write = input('Would you like to overwrite the value of var_2?:\n')

if over_write == 'yes':
    var_2 = int(input('what is the new value of var_2?:\n'))
    print(var_2)
    correct = input('Is this the correct value for var_2?:\n')
    if correct == 'yes':
        pass #this will make the code continue to run without exiting

print('Prompt #4 & Prompt #5:\n')
print('Type of variable for var_1:', type(var_1))
print('Type of variable for var_2:', type(var_2))
print('Type of variable for var_3:', type(var_3))
print('Type of variable for var_4:', type(var_4))

print('The reason var_1 and var_3 are different variables is because an integer may not contain decimal places (as in var_2), while a float contains decimal places (as in var_3). In python, data types and variables are assigned based on this logic.\n')

print('Prompt #6:')
# order of opperations example
math_result = var_1 * var_1 + var_3
print(math_result)
print('The reason the result is 22 is because many programming languages such as python evaluate math functions per order of opperations.\n')

print('Prompt #7 - Prompt #10:\n')
# var_1 squared:
var_1_sqaured = var_1 **2
print(var_1_sqaured)
# var_3 / var_1:
floor_division = var_3 // var_1
print(floor_division)
# modulus var_4 / var_1:
modulus_division = var_4 % var_1
print(modulus_division)

print('The difference bewtween modulus division and floor division is that modulus division returns the remainder of the quotient, while floor division returns the rounded answer without remainders.\n')